### PR TITLE
18 module ataru

### PR DESCRIPTION
**Pull request by madziaf**
hi Team, 
have a look if the changes solve #18 already.

### CODE REVIEW

**Comment by madziaf** [comment]
thanks Ernesto!

**Comment by madziaf** [comment]
ataru works now like that:
`bin/ataru gogo test.md`

**Comment by emig** [comment]
No new commit has been provided yet, so by reopening the pull request, Travis is running the latest commit available on the branch  1442374

**Comment by nanoparsec** [comment]
Solved isue #18

**Pull request merged**
