### PR TITLE
use instance of ArgumentChecker and block

### LINKED ISSUE #27: extract the block content into a method
in order not to iterate over ARGV array twice
and be able to call this method from Rake task

### PR DESCRIPTION
**Pull request by madziaf**
hopefully resolves #27

### CODE REVIEW

**Comment by schultyy** [comment]
Sieht gut aus. Can be merged. Well done Magda :) :+1:

**Comment by code-later** [comment]
giphy

**Comment by moonglum** [comment]
Awesome! :+1: 

Impressed Dude

**Comment by madziaf** [comment]
omg, can we re-use those gifs..? :)))))))))

**Comment by madziaf** [comment]
btw, that's how i dance sometimes ;)

**Comment by code-later** [comment]
GIFs are of course free for re-use :-)

**Comment by moonglum** [comment]
Of course you can reuse them! This is how you build your GIF collection :wink:
Awesome :smiley_cat:

**Pull request merged**
