### PR TITLE
created ArgumentChecker, Application, changed exit code nb with method for checking input files and Applica...

### PR DESCRIPTION
**Pull request by madziaf**
created ArgumentChecker with method for checking input files and Application class with method for running checked files, changed exit code numbers
issues #25 
#26
#27

### CODE REVIEW

**Comment by code-later** [comment]
@madziaf and @NerdBabe, that is pretty impressive what you did here. Very well done.

**Comment by schultyy** [comment]
@madziaf wow, you're so fast :) Looks good for me. Can be merged.

**Comment by moonglum** [comment]
67c3c612-8d07-11e3-8746-750139705dbe

**Comment by code-later** [comment]
Best GIF for this!

**Comment by schultyy** [comment]
giphy
^^ (was ein akt so ein gif hier rein zu bekommen)

**Comment by nanoparsec** [comment]
Meh, and I spend the whole day with pxelschubsen -.- Now I feel ugly. :)

2014-08-18 22:40 GMT+02:00 Jan Schulte notifications@github.com:

> http://media.giphy.com/media/11gstpTtEAU4nu/giphy.gif
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CodePadawans/ataru/pull/31#issuecomment-52551746.

## 

_--------------_
_nerdbabe_

_Personal Contact Information_
_Email: mail@nerdbabe.de mail@nerdbabe.de_
_Website: nerdbabe.de http://nerdbabe.de_
_Twitter: *nerdbabe
https://mail.google.com/mail/ca/u/0/https//:twitter.com/nerdbabe
*Github:_ NerdBabe https://github.com/NerdBabe

**Comment by schultyy** [comment]
@NerdBabe ach kaese :) Du zauberst immer sehr tolle Bilder :)

**Comment by madziaf** [comment]
yeah!!!
resolves #25 #26 #27

**Comment by madziaf** [comment]
how do one closes the issues with the merge together? khyyy...

**Comment by moonglum** [comment]
@madziaf You can actually transform an issue into a pull request. 

:warning: :rabbit:hole warning :warning:
1. Install [hub](https://hub.github.com). Try to install it with your package manager (if it doesn't have it, you have to install from source as described on the page), then in your zsh configuration set `alias git=hub`. If everything worked, then `git version` should output both a version for git and for hub.
2. Your git command now continues to work as it did before – but it has super powers: It knows that Github exists! There are a lot of different things you can do with it, but I will only describe the one that you asked for.
3. When you worked on a feature, push it to a remote branch. While you are on that branch, run `git pull-request -i TICKET_NUMBER`, where the TICKET_NUMBER is the ID of the issue you want to convert into a pull request.
4. Visit the ticket again and it magically was transformed into a pull request.

[This is actually how I do the work on all my projects.]

**Comment by schultyy** [comment]
@moonglum That's the magic trick 👻 all the people do? ^^

**Comment by moonglum** [comment]
@schultyy Yes, indeed!

**Comment by nanoparsec** [comment]
cool. seems that i have to give up my github client :)

Am Dienstag, 19. August 2014 schrieb Lucas Dohmen :

> @schultyy https://github.com/schultyy Yes, indeed!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/CodePadawans/ataru/pull/31#issuecomment-52601604.

## 

_--------------_
_nerdbabe_

_Personal Contact Information_
_Email: mail@nerdbabe.de mail@nerdbabe.de_
_Website: nerdbabe.de http://nerdbabe.de_
_Twitter: *nerdbabe
https://mail.google.com/mail/ca/u/0/https//:twitter.com/nerdbabe
*Github:_ NerdBabe https://github.com/NerdBabe

**Comment by code-later** [comment]
The shell is a cozy place to be. You give up one client but get another one in return :-)

**Pull request merged**
