### PR TITLE
added checking for # =>

### PR DESCRIPTION
**Pull request by madziaf**

### CODE REVIEW

**Comment by moonglum** [comment]
@emig What you are saying is that you only want one RegExp in the entire method, right?

**Comment by moonglum** [comment]
Or do you want to remove one matchgroup?

**Comment by emig** [comment]
I am refering to keeping just one matchgroup per regex on lines lib/ataru/test_converter.rb:L14-L15. This will make innecessary to modify lib/ataru/test_converter.rb:L25-L26

**Comment by moonglum** [comment]
Ok, I totally agree, @emig :+1: This could be either done now or in a separate refactoring step.

**Comment by emig** [comment]
For a later refactor :) I  merge the commit then!

**Comment by moonglum** [comment]
Agreed :+1:

**Pull request merged**
